"""
Django settings for spotify_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5ut1f48y_n918z_l&sa3x2=c4rw9=t)elaa3f1%n79^@k_3p!e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken', #Token tabanlı kimlik doğrulama için
    'accounts',#accounts uygulaması
    'music',#music uygulaması,
    'corsheaders', # CORS ayarları için
    'rest_framework_simplejwt'
]

CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', # BU SATIRI EN BAŞA YAKIN BİR YERE KOYUN
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spotify_project.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'templates'],   # <-- proje düzeyinde templates klasörü
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
    },
}]

WSGI_APPLICATION = 'spotify_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DB_TYPE') == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),      # Veritabanı adı
            'USER': os.environ.get('DB_USER'),      # Kullanıcı adı
            'PASSWORD': os.environ.get('DB_PASSWORD'), # Şifre
            'HOST': os.environ.get('DB_HOST'),      # Kubernetes servis adı (postgres-service)
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    # Local ortamda veya Docker Compose ile çalışırken burası devreye girer
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Simple JWT Ayarları
SIMPLE_JWT = {
    # Access Token'ın geçerlilik süresini 3 saat yap
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=3), 

    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

    # Diğer varsayılan ayarlar (isteğe bağlı, Simple JWT dokümantasyonunda detayları var)
    # 'AUTH_HEADER_TYPES': ('Bearer',), # Frontend'den gelen 'Bearer' ön ekini kabul eder
    # 'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    # 'USER_ID_FIELD': 'id',
    # 'USER_ID_CLAIM': 'user_id',
    # ...
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# settings.py

REST_FRAMEWORK = { #Rest framework ayarları
    "DEFAULT_AUTHENTICATION_CLASSES": [ #Token tabanlı kimlik doğrulama
        # 🛑 DÜZELTME: TokenAuthentication, 'Bearer' ön ekini desteklemez.
        # Bu nedenle, 'Bearer' destekleyen JWTAuthentication'a geçiyoruz:
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    "DEFAULT_PERMISSION_CLASSES": [#Tüm isteklere kimlik doğrulama zorunluluğu
        "rest_framework.permissions.IsAuthenticated",
        # Ama biz Register/Login view’lerinde override edip AllowAny verdik
    ]
}



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # (opsiyonel: proje içi statikler)

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User" #Custom user modelimizi kullanmak için

# medya dosyaları (mp3) için
from pathlib import Path
import os
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Docker içinde çalıştığımız için service adını (master) kullanıyoruz.
SEAWEEDFS_MASTER_URL = os.environ.get('SEAWEEDFS_MASTER_URL', "http://master:9333")