# Generated by Django 5.2.7 on 2026-02-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tür'),
        ),
        migrations.AddField(
            model_name='song',
            name='popularity',
            field=models.PositiveIntegerField(default=0, verbose_name='Popülerlik Skoru'),
        ),
    ]
